# Generated by Django 5.2.1 on 2025-05-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptofacts',
            name='video',
        ),
        migrations.RemoveField(
            model_name='hobbies',
            name='video',
        ),
    ]
